#Main CDK stack: Cognito, DynamoDB, Lambdas, Step Functions, HTTP API.
from aws_cdk import (
    Duration,
    RemovalPolicy,
    Stack,
    CfnOutput,
    aws_apigatewayv2 as apigwv2,
    aws_apigatewayv2_authorizers as apigwv2_authorizers,
    aws_apigatewayv2_integrations as apigwv2_integrations,
    aws_cognito as cognito,
    aws_dynamodb as ddb,
    aws_events as events,
    aws_events_targets as event_targets,
    aws_iam as iam,
    aws_lambda as _lambda,
    aws_logs as logs,
    aws_stepfunctions as sfn,
    aws_stepfunctions_tasks as sfn_tasks,
)
from constructs import Construct


class VpcApiStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # ------------------------------------------------------------------
        # 1. Cognito User Pool (auth)
        # ------------------------------------------------------------------
        user_pool = cognito.UserPool(
            self,
            "VpcApiUserPool",
            self_sign_up_enabled=True,
            sign_in_aliases=cognito.SignInAliases(email=True),
            auto_verify=cognito.AutoVerifiedAttrs(email=True),
            password_policy=cognito.PasswordPolicy(
                min_length=10,
                require_lowercase=True,
                require_uppercase=True,
                require_digits=True,
                require_symbols=False,
            ),
            account_recovery=cognito.AccountRecovery.EMAIL_ONLY,
            removal_policy=RemovalPolicy.DESTROY,  # demo only — switch to RETAIN in prod
        )

        user_pool_client = user_pool.add_client(
            "VpcApiUserPoolClient",
            auth_flows=cognito.AuthFlow(user_password=True, user_srp=True),
            generate_secret=False,
            id_token_validity=Duration.hours(1),
            refresh_token_validity=Duration.days(30),
        )

        # ------------------------------------------------------------------
        # 2. DynamoDB table — stores VPC job records
        # ------------------------------------------------------------------
        # PK: vpcId (UUID generated by the API).
        # GSI: ownerSub  -> list-per-user queries
        table = ddb.Table(
            self,
            "VpcRecordsTable",
            partition_key=ddb.Attribute(name="vpcId", type=ddb.AttributeType.STRING),
            billing_mode=ddb.BillingMode.PAY_PER_REQUEST,
            point_in_time_recovery_specification=ddb.PointInTimeRecoverySpecification(
                point_in_time_recovery_enabled=True
            ),
            removal_policy=RemovalPolicy.DESTROY,  # demo only
        )
        table.add_global_secondary_index(
            index_name="byOwner",
            partition_key=ddb.Attribute(name="ownerSub", type=ddb.AttributeType.STRING),
            sort_key=ddb.Attribute(name="createdAt", type=ddb.AttributeType.STRING),
        )
        table.add_global_secondary_index(
            index_name="byTeam",
            partition_key=ddb.Attribute(name="team", type=ddb.AttributeType.STRING),
            sort_key=ddb.Attribute(name="createdAt", type=ddb.AttributeType.STRING),
        )

        # Cognito group — members of this group can create, modify, and delete VPCs.
        cognito.CfnUserPoolGroup(
            self,
            "VpcAdminsGroup",
            user_pool_id=user_pool.user_pool_id,
            group_name="vpc-admins",
            description="Users with permission to create, modify, and delete VPCs",
        )

        # ------------------------------------------------------------------
        # 3. Workflow Lambdas (run inside Step Functions)
        # ------------------------------------------------------------------
        workflow_env = {"TABLE_NAME": table.table_name}

        create_vpc_task = _lambda.Function(
            self,
            "CreateVpcTaskFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="create_vpc_resource.handler",
            code=_lambda.Code.from_asset("lambdas/workflow"),
            timeout=Duration.seconds(60),
            environment=workflow_env,
            log_group=logs.LogGroup(
                self,
                "CreateVpcTaskFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )
        create_subnet_task = _lambda.Function(
            self,
            "CreateSubnetTaskFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="create_subnets.handler",
            code=_lambda.Code.from_asset("lambdas/workflow"),
            timeout=Duration.seconds(60),
            environment=workflow_env,
            log_group=logs.LogGroup(
                self,
                "CreateSubnetTaskFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )
        finalize_task = _lambda.Function(
            self,
            "FinalizeTaskFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="finalize.handler",
            code=_lambda.Code.from_asset("lambdas/workflow"),
            timeout=Duration.seconds(30),
            environment=workflow_env,
            log_group=logs.LogGroup(
                self,
                "FinalizeTaskFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )
        finalize_add_subnets_task = _lambda.Function(
            self,
            "FinalizeAddSubnetsTaskFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="finalize_add_subnets.handler",
            code=_lambda.Code.from_asset("lambdas/workflow"),
            timeout=Duration.seconds(30),
            environment=workflow_env,
            log_group=logs.LogGroup(
                self,
                "FinalizeAddSubnetsTaskFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )

        # EC2 permissions for the VPC-provisioning workflow Lambdas — split by action so each can carry the tightest possible condition.
        # CreateVpc: require the vpc-api:jobId tag to be present in the request, preventing the Lambda from creating untagged/untracked VPCs.
        create_vpc_task.add_to_role_policy(iam.PolicyStatement(
            actions=["ec2:CreateVpc"],
            resources=["*"],
            conditions={"StringLike": {"aws:RequestTag/vpc-api:jobId": "*"}},
        ))
        # CreateTags at VPC-creation time only (not as a standalone tag operation).
        create_vpc_task.add_to_role_policy(iam.PolicyStatement(
            actions=["ec2:CreateTags"],
            resources=["*"],
            conditions={"StringEquals": {"ec2:CreateAction": "CreateVpc"}},
        ))
        # DescribeVpcs cannot be scoped to specific resources — must stay broad.
        create_vpc_task.add_to_role_policy(iam.PolicyStatement(
            actions=["ec2:DescribeVpcs"],
            resources=["*"],
        ))
        # ModifyVpcAttribute: only on VPCs that carry our tag.
        create_vpc_task.add_to_role_policy(iam.PolicyStatement(
            actions=["ec2:ModifyVpcAttribute"],
            resources=["*"],
            conditions={"StringLike": {"ec2:ResourceTag/vpc-api:jobId": "*"}},
        ))

        # CreateSubnet on the new subnet resource: require our tag to be applied at creation time.
        create_subnet_task.add_to_role_policy(iam.PolicyStatement(
            actions=["ec2:CreateSubnet"],
            resources=["arn:aws:ec2:*:*:subnet/*"],
            conditions={"StringLike": {"aws:RequestTag/vpc-api:jobId": "*"}},
        ))
        
        # CreateSubnet on the parent VPC resource: require the VPC to already carry our tag.
        # AWS evaluates ec2:CreateSubnet against both the subnet being created and the parent VPC, so both resources need an explicit allow with matching conditions.
        create_subnet_task.add_to_role_policy(iam.PolicyStatement(
            actions=["ec2:CreateSubnet"],
            resources=["arn:aws:ec2:*:*:vpc/*"],
            conditions={"StringLike": {"ec2:ResourceTag/vpc-api:jobId": "*"}},
        ))
        # CreateTags at subnet-creation time only.
        create_subnet_task.add_to_role_policy(iam.PolicyStatement(
            actions=["ec2:CreateTags"],
            resources=["*"],
            conditions={"StringEquals": {"ec2:CreateAction": "CreateSubnet"}},
        ))

        table.grant_read_write_data(create_vpc_task)
        table.grant_read_write_data(finalize_task)
        table.grant_read_write_data(finalize_add_subnets_task)

        # ------------------------------------------------------------------
        # 4. Step Functions state machines
        # ------------------------------------------------------------------

        # ── 4a. VPC provisioning (create VPC + subnets) ───────────────────
        create_vpc_state = sfn_tasks.LambdaInvoke(
            self,
            "CreateVpc",
            lambda_function=create_vpc_task,
            payload_response_only=True,
            result_path="$.vpc",
        )

        # Map state — one subnet creation invocation per requested subnet.
        subnet_map = sfn.Map(
            self,
            "CreateSubnets",
            items_path=sfn.JsonPath.string_at("$.subnets"),
            max_concurrency=10,
            item_selector={
                "vpcId.$": "$.vpc.vpcId",
                "jobId.$": "$.jobId",
                "subnet.$": "$$.Map.Item.Value",
            },
            result_path="$.createdSubnets",
        )
        subnet_map.item_processor(
            sfn_tasks.LambdaInvoke(
                self,
                "CreateSubnet",
                lambda_function=create_subnet_task,
                payload_response_only=True,
            )
        )

        finalize_success = sfn_tasks.LambdaInvoke(
            self,
            "FinalizeSuccess",
            lambda_function=finalize_task,
            payload=sfn.TaskInput.from_object(
                {
                    "jobId.$": "$.jobId",
                    "status": "SUCCEEDED",
                    "vpc.$": "$.vpc",
                    "subnets.$": "$.createdSubnets",
                }
            ),
            payload_response_only=True,
        )

        finalize_failure = sfn_tasks.LambdaInvoke(
            self,
            "FinalizeFailure",
            lambda_function=finalize_task,
            payload=sfn.TaskInput.from_object(
                {
                    "jobId.$": "$.jobId",
                    "status": "FAILED",
                    "error.$": "$.errorInfo",
                }
            ),
            payload_response_only=True,
        )

        definition = create_vpc_state.next(subnet_map).next(finalize_success)

        # Catch errors from any state and write FAILED record.
        create_vpc_state.add_catch(finalize_failure, result_path="$.errorInfo")
        subnet_map.add_catch(finalize_failure, result_path="$.errorInfo")
        finalize_success.add_catch(finalize_failure, result_path="$.errorInfo")

        state_machine = sfn.StateMachine(
            self,
            "VpcProvisioningStateMachine",
            definition_body=sfn.DefinitionBody.from_chainable(definition),
            timeout=Duration.minutes(15),
            tracing_enabled=True,
        )

        # ── 4b. Add-subnets (append subnets to an existing VPC) ───────────
        # Reuses create_subnet_task; maps awsVpcId → vpcId for the iterator.
        add_subnet_map = sfn.Map(
            self,
            "AddSubnets",
            items_path=sfn.JsonPath.string_at("$.subnets"),
            max_concurrency=10,
            item_selector={
                "vpcId.$": "$.awsVpcId",
                "jobId.$": "$.jobId",
                "subnet.$": "$$.Map.Item.Value",
            },
            result_path="$.createdSubnets",
        )
        add_subnet_map.item_processor(
            sfn_tasks.LambdaInvoke(
                self,
                "AddSubnet",
                lambda_function=create_subnet_task,
                payload_response_only=True,
            )
        )

        finalize_add_success = sfn_tasks.LambdaInvoke(
            self,
            "FinalizeAddSubnetsSuccess",
            lambda_function=finalize_add_subnets_task,
            payload=sfn.TaskInput.from_object(
                {
                    "jobId.$": "$.jobId",
                    "status": "SUCCEEDED",
                    "newSubnets.$": "$.createdSubnets",
                }
            ),
            payload_response_only=True,
        )

        finalize_add_failure = sfn_tasks.LambdaInvoke(
            self,
            "FinalizeAddSubnetsFailure",
            lambda_function=finalize_add_subnets_task,
            payload=sfn.TaskInput.from_object(
                {
                    "jobId.$": "$.jobId",
                    "status": "FAILED",
                    "error.$": "$.errorInfo",
                }
            ),
            payload_response_only=True,
        )

        add_subnets_definition = add_subnet_map.next(finalize_add_success)
        add_subnet_map.add_catch(finalize_add_failure, result_path="$.errorInfo")
        finalize_add_success.add_catch(finalize_add_failure, result_path="$.errorInfo")

        add_subnets_state_machine = sfn.StateMachine(
            self,
            "AddSubnetsStateMachine",
            definition_body=sfn.DefinitionBody.from_chainable(add_subnets_definition),
            timeout=Duration.minutes(10),
            tracing_enabled=True,
        )

        # ------------------------------------------------------------------
        # 5. Background reconciler
        # ------------------------------------------------------------------
        reconcile_fn = _lambda.Function(
            self,
            "ReconcileVpcsFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="reconcile_vpcs.handler",
            code=_lambda.Code.from_asset("lambdas/workflow"),
            timeout=Duration.minutes(5),
            environment={"TABLE_NAME": table.table_name},
            log_group=logs.LogGroup(
                self,
                "ReconcileVpcsFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )

        # ------------------------------------------------------------------
        # 6. API Lambdas
        # ------------------------------------------------------------------
        api_env = {
            "TABLE_NAME": table.table_name,
            "STATE_MACHINE_ARN": state_machine.state_machine_arn,
            "OWNER_INDEX_NAME": "byOwner",
            "TEAM_INDEX_NAME": "byTeam",
            "DEFAULT_AZ": f"{self.region}a",
        }

        create_vpc_api = _lambda.Function(
            self,
            "CreateVpcApiFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="create_vpc.handler",
            code=_lambda.Code.from_asset("lambdas/api"),
            timeout=Duration.seconds(15),
            environment=api_env,
            log_group=logs.LogGroup(
                self,
                "CreateVpcApiFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )
        get_vpc_api = _lambda.Function(
            self,
            "GetVpcApiFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="get_vpc.handler",
            code=_lambda.Code.from_asset("lambdas/api"),
            timeout=Duration.seconds(10),
            environment=api_env,
            log_group=logs.LogGroup(
                self,
                "GetVpcApiFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )
        list_vpcs_api = _lambda.Function(
            self,
            "ListVpcsApiFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="list_vpcs.handler",
            code=_lambda.Code.from_asset("lambdas/api"),
            timeout=Duration.seconds(10),
            environment=api_env,
            log_group=logs.LogGroup(
                self,
                "ListVpcsApiFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )
        delete_vpc_api = _lambda.Function(
            self,
            "DeleteVpcApiFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="delete_vpc.handler",
            code=_lambda.Code.from_asset("lambdas/api"),
            timeout=Duration.seconds(30),  # may need to delete many subnets
            environment={"TABLE_NAME": table.table_name},
            log_group=logs.LogGroup(
                self,
                "DeleteVpcApiFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )
        delete_subnet_api = _lambda.Function(
            self,
            "DeleteSubnetApiFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="delete_subnet.handler",
            code=_lambda.Code.from_asset("lambdas/api"),
            timeout=Duration.seconds(15),
            environment={"TABLE_NAME": table.table_name},
            log_group=logs.LogGroup(
                self,
                "DeleteSubnetApiFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )
        add_subnets_api = _lambda.Function(
            self,
            "AddSubnetsApiFn",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="add_subnets.handler",
            code=_lambda.Code.from_asset("lambdas/api"),
            timeout=Duration.seconds(15),
            environment={
                "TABLE_NAME": table.table_name,
                "ADD_SUBNETS_STATE_MACHINE_ARN": add_subnets_state_machine.state_machine_arn,
                "DEFAULT_AZ": f"{self.region}a",
            },
            log_group=logs.LogGroup(
                self,
                "AddSubnetsApiFnLogs",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=RemovalPolicy.DESTROY,
            ),
        )

        # EC2 delete permissions — restricted to resources that carry our tag preventing deletion of VPCs/subnets created outside API
        ec2_delete_policy = iam.PolicyStatement(
            actions=["ec2:DeleteVpc", "ec2:DeleteSubnet"],
            resources=["*"],
            conditions={"StringLike": {"ec2:ResourceTag/vpc-api:jobId": "*"}},
        )

        table.grant_read_write_data(create_vpc_api)
        table.grant_read_write_data(get_vpc_api)
        table.grant_read_data(list_vpcs_api)
        table.grant_read_write_data(reconcile_fn)
        table.grant_read_write_data(delete_vpc_api)
        table.grant_read_write_data(delete_subnet_api)
        table.grant_read_write_data(add_subnets_api)

        state_machine.grant_start_execution(create_vpc_api)
        add_subnets_state_machine.grant_start_execution(add_subnets_api)

        delete_vpc_api.add_to_role_policy(ec2_delete_policy)
        delete_subnet_api.add_to_role_policy(ec2_delete_policy)

        # DescribeVpcs/DescribeSubnets cannot be scoped to specific resources.
        ec2_describe_policy = iam.PolicyStatement(
            actions=["ec2:DescribeVpcs", "ec2:DescribeSubnets"],
            resources=["*"],
        )
        get_vpc_api.add_to_role_policy(ec2_describe_policy)
        reconcile_fn.add_to_role_policy(ec2_describe_policy)

        # EventBridge rule — trigger the reconciler every 5 minutes.
        reconcile_rule = events.Rule(
            self,
            "ReconcileSchedule",
            schedule=events.Schedule.rate(Duration.minutes(5)),
        )
        reconcile_rule.add_target(event_targets.LambdaFunction(reconcile_fn))

        # ------------------------------------------------------------------
        # 6. HTTP API + Cognito JWT authorizer
        # ------------------------------------------------------------------
        http_api = apigwv2.HttpApi(
            self,
            "VpcHttpApi",
            description="VPC provisioning API",
            cors_preflight=apigwv2.CorsPreflightOptions(
                allow_methods=[apigwv2.CorsHttpMethod.ANY],
                allow_origins=["*"],
                allow_headers=["Authorization", "Content-Type"],
            ),
        )

        jwt_authorizer = apigwv2_authorizers.HttpUserPoolAuthorizer(
            "CognitoAuthorizer",
            user_pool,
            user_pool_clients=[user_pool_client],
        )

        http_api.add_routes(
            path="/vpcs",
            methods=[apigwv2.HttpMethod.POST],
            integration=apigwv2_integrations.HttpLambdaIntegration(
                "CreateVpcIntegration", create_vpc_api
            ),
            authorizer=jwt_authorizer,
        )
        http_api.add_routes(
            path="/vpcs",
            methods=[apigwv2.HttpMethod.GET],
            integration=apigwv2_integrations.HttpLambdaIntegration(
                "ListVpcsIntegration", list_vpcs_api
            ),
            authorizer=jwt_authorizer,
        )
        http_api.add_routes(
            path="/vpcs/{id}",
            methods=[apigwv2.HttpMethod.GET],
            integration=apigwv2_integrations.HttpLambdaIntegration(
                "GetVpcIntegration", get_vpc_api
            ),
            authorizer=jwt_authorizer,
        )
        http_api.add_routes(
            path="/vpcs/{id}",
            methods=[apigwv2.HttpMethod.DELETE],
            integration=apigwv2_integrations.HttpLambdaIntegration(
                "DeleteVpcIntegration", delete_vpc_api
            ),
            authorizer=jwt_authorizer,
        )
        http_api.add_routes(
            path="/vpcs/{id}/subnets/{subnetId}",
            methods=[apigwv2.HttpMethod.DELETE],
            integration=apigwv2_integrations.HttpLambdaIntegration(
                "DeleteSubnetIntegration", delete_subnet_api
            ),
            authorizer=jwt_authorizer,
        )
        http_api.add_routes(
            path="/vpcs/{id}/subnets",
            methods=[apigwv2.HttpMethod.POST],
            integration=apigwv2_integrations.HttpLambdaIntegration(
                "AddSubnetsIntegration", add_subnets_api
            ),
            authorizer=jwt_authorizer,
        )

        # ------------------------------------------------------------------
        # 7. Outputs
        # ------------------------------------------------------------------
        CfnOutput(self, "ApiUrl", value=http_api.api_endpoint)
        CfnOutput(self, "UserPoolId", value=user_pool.user_pool_id)
        CfnOutput(self, "UserPoolClientId", value=user_pool_client.user_pool_client_id)
        CfnOutput(self, "TableName", value=table.table_name)
        CfnOutput(self, "StateMachineArn", value=state_machine.state_machine_arn)
        CfnOutput(
            self,
            "AddSubnetsStateMachineArn",
            value=add_subnets_state_machine.state_machine_arn,
        )
